import { Case, Officer } from "../../pages/dynamic/dynamicPages";
import {
  Cases,
  Home,
  Officers,
  ReportCase,
  Account,
  SignIn,
  SingUp,
  CreateOfficer
} from "../../pages/single/singlePages";

export const SINGLE_PAGES_CONFIG = [
  {
    path: "/",
    slug: "",
    title: "Главная",
    description: "Главная страница",
    component: <Home />,
    isNav: false,
    navTitle: "Главная",
    isMobileNav: true,
    isPublicNav: false,
  },
  {
    path: "/sign-in",
    slug: "sign-in",
    title: "Вход",
    description: "Вход в личной кабинет",
    component: <SignIn />,
    isNav: false,
    navTitle: "Войти",
    isMobileNav: false,
    isPublicNav: false,
  },
  {
    path: "/sign-up",
    slug: "sign-up",
    title: "Регистрация",
    description: "Регистрация в личном кабинете",
    component: <SingUp />,
    isNav: false,
    navTitle: "Регистрация",
    isMobileNav: false,
    isPublicNav: false,
  },
  {
    path: "/account",
    slug: "account",
    title: "Личный аккаунт",
    description: "Ваш личный аккаунт",
    component: <Account />,
    isNav: false,
    navTitle: "Личный кабинет",
    isMobileNav: false,
    isPublicNav: false,
  },
  {
    path: "/report",
    slug: "report",
    title: "Сообщить о краже",
    description: "Сообщите о краже велосипеда",
    component: <ReportCase />,
    isNav: true,
    navTitle: "Сообщить о краже",
    isMobileNav: true,
    isPublicNav: true,
  },
  {
    path: "/cases",
    slug: "cases",
    title: "Сообщения о кражах",
    description: "Список всех сообщений о кражах",
    component: <Cases />,
    isNav: true,
    navTitle: "Сообщения о кражах",
    isMobileNav: true,
    isPublicNav: false,
  },
  {
    path: "/officers",
    slug: "officers",
    title: "Ответственные сотрудники",
    description: "Список всех ответственных сотрудников",
    component: <Officers />,
    isNav: true,
    navTitle: "Сотрудники Bike-Share",
    isMobileNav: true,
    isPublicNav: false,
  },
  {
    path: "/create-officer",
    slug: "create-officer",
    title: "Добавить сотрудника",
    description: "Добавление ответственного сотрудника",
    component: <CreateOfficer />,
    isNav: false,
    navTitle: "",
    isMobileNav: false,
    isPublicNav: false,
  },
];

export const DYNAMIC_PAGES_CONFIG = [
  {
    path: "/cases",
    title: "Случай о краже",
    description: "Случай о краже",
    component: <Case />,
  },

  {
    path: "/officers",
    title: "Ответственный сотрудник",
    description: "Страничка ответственного сотрудника",
    component: <Officer />,
  },
];
